---
title: "Beer and Brew Project"
author: "Xavier Mojica"
date: "2022-10-15"
output: 
  html_document: default
  
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Beer and Brewery Data
## Presenting Findings of Beer and Breweries 

```{r}
library(e1071)
library(caret)
library(class)
library(tidyverse)
library(stringr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(knitr)
library(rmarkdown)

#Reading our Beer and Brewery Files
totalBeer = read.csv('~/Dropbox/Mac/Desktop/Desktop/Intro-DataScience/Unit7/Unit8and9/Beers.csv', header = TRUE)
totalBrew = read.csv('~/Dropbox/Mac/Desktop/Desktop/Intro-DataScience/Unit7/Unit8and9/Breweries.csv', header = TRUE)
head(totalBeer)
head(totalBrew)

```
```{r}
#1) How many breweries are present in each state?
totalBrew %>% group_by(State) %>% count(State)
ggplot(totalBrew, aes(x = State), fill = State) + geom_bar() + labs(title ="Amount of Breweries per State", x = "States", y = "Amount of Breweries")
```
```{r}
#2) Merging Beer and Brewery data
#Checking dimensions of both dataframes 
dim(totalBeer)
dim(totalBrew)

#Merging Beer is totalBeer and Brewery is totalBrew.
mergedB = merge(totalBeer, totalBrew, by.x = "Brewery_id", by.y = "Brew_ID")
dim(mergedB)

#Looking at the first 6 observations.
head(mergedB, n=6)

#Looking at the last 6 observations.
tail(mergedB, n = 6)
```
```{r}
#3)	Addressing the missing values in each column.
##Cleaning up data by removing NAs. 
mergedB = na.omit(mergedB)
dim(mergedB)
```
```{r}
#4)	Computing the median Alcohol Content (ABV) and International Bitterness Unit (IBU) for each state. Plot a bar chart to compare.
#This gives us the median for alcohol content.
medianABV = median(mergedB$ABV)

#Getting the median of bitterness is given by this code. 
medianIBU = median(mergedB$IBU)

medFrame = mergedB %>% group_by(State) %>% summarise(medianABV = median(ABV), medianIBU = median(IBU))

#Plotting via bar charts, shows the Median ABV per State.
ggplot(medFrame, aes(x = State, y = medianABV)) + geom_bar(stat = 'identity') + labs(title = "Median ABV per State", y = "Median ABV")

#This will give us the Median IBU per State. 
ggplot(medFrame, aes(x = State, y = medianIBU), color = "yellow") + geom_bar(stat = 'identity') + labs(title = "Median IBU per State", y = "Median IBU")
```
```{r}
#5) Which state has the maximum alcoholic (ABV) beer? 
##Arranging the rows in descending order with reference to ABV.
arrange(medFrame, desc(medianIBU))

#Which state has the most bitter (IBU) beer?
#Arranging the rows in descending order with reference to IBU.
arrange(medFrame, desc(medianABV))

```
```{r}
#6) Comment on the summary statistics and distribution of the ABV variable.
#Most beers average around 0.052. Looking at the overall distribution, the data 
#is right skewed. Our max for ABV is at 0.12500 and min is 0.02700.
ggplot(mergedB, aes(x = ABV)) + geom_histogram() + labs(title = "ABV Distribution", y = "Count")

```
```{r}
#7) The relationship between the bitterness of the beer and its alcoholic content.
#Using a scatter plot we look into their relationship.
#The relationship between ABV and IBU appears to be linear and positive. There 
#are many outliers (noise) from what can be seen. 

ggplot(mergedB, aes(x = ABV, y = IBU)) + geom_point(size = 0.1) + geom_jitter() + stat_smooth(method = 'lm') + labs(title = "ABV vs. IBU")
```
```{r}
#8) Investigating the difference between IPAs and Ale with respect to IBU and ABV. 

#This guarantees the same values are produced.  
set.seed(7)

#Using grepl to find rows that contain IPA and Ale within the Style column. 
mergedBall= mergedB %>% filter(grepl("IPA|Ale", Style))

#Grabbing and then categorizing all Ales and IPAs through each row within the Sytle Column. 
for (i in 1:length(mergedBall$Style))
  {
  if (grepl("IPA", mergedBall$Style[i]))
    {
    mergedBall$group[i]= "IPA"
  } else{
    mergedBall$group[i] = "Ale"
  }
}

mergedBall

#Creating the training and testing for IBU and ABV. Training the model. 
trainIndices = sample(1:dim(mergedBall)[1], round(0.75* dim(mergedBall)[1]))
train = mergedBall[trainIndices,]
test = mergedBall[-trainIndices,]

#Seeing visually how Ales and IPAs interact with a scatter plot.  
mergedBall %>% ggplot(aes(x = IBU, y = ABV, color = group)) + geom_point() + geom_jitter()

```

```{r}

#This code chuck will loop through each iteration in order to find the best accuracy 
#for the k value. Once the best value is found it will be used in the next code chunk. 
iterations = 500
numks = 30
masterAcc = matrix(nrow = iterations, ncol = numks)

for(j in 1:iterations)
{
  accs = data.frame(accuracy = numeric(30), k = numeric(30))
  trainIndices = sample(1:dim(mergedBall)[1], round(0.75* dim(mergedBall)[1]))
  train = mergedBall[trainIndices,]
  test = mergedBall[-trainIndices,]
  for(i in 1:numks)
  {
    classifications = knn(train[,c(4,5)], test[,c(4,5)], train$group, prob = TRUE, k =3)
    table(classifications, test$group)
    cm = confusionMatrix(table(classifications, test$group))
    masterAcc[j,i] = cm$overall[1]
  }
}
MeanAcc = colMeans(masterAcc)
plot(seq(1,numks,1),MeanAcc, type = "l")
```

```{r}
#k = 23 is the max k value that gives us the best accuracy for the model 
classifications = knn(train[,c(4,5)], test[,c(4,5)], train$Style, prob = TRUE, k =23)
table(classifications, test$Style)
cm = confusionMatrix(table(classifications, test$Style))
cm 
# The model reports an Accuracy of 84.75% 
```

```{r}

#Predicting to see if our data point will be an IPA or Ale using a low ABV and low IBU values
df_test = data.frame(ABV = 0.1 , IBU = 10 )

classifications = knn(train[,c(4,5)], df_test, train$group, prob = TRUE, k =3)
classifications 
#our model shows that the probably of it being an Ale as a 66% Accuracy 


#Using higher ABV and IBU values to test to see if those values give us an IPA
df_test = data.frame(ABV = 0.31 , IBU = 50 )

classifications = knn(train[,c(4,5)], df_test, train$group, prob = TRUE, k =3)
classifications 
# The model predicts that it will be an IPA with a prob of 66%.
# It would seem that higher the IBU and ABV are, the higher the indicator is of
# a data point to be an IPA. 

#IPA has a higher average for ABV and IBU whilst Ale appears to have a lower average for ABV and IBU.
#This statistically reinforces the observation of IPA and Ales traits and/or relationship. 
mergedBall %>% group_by(group) %>% summarise(meanABV = mean(ABV), meanIBU = mean(IBU))

```

```{r}
#9 Looking for eligible states for appropriate target market using ABV. If you want to make an IPA here are the states Budweiser should invest in. 
mergedBall %>% group_by(State) %>% summarise(meanABV = mean(ABV)) %>% arrange(desc(meanABV)) %>% 
  ggplot(aes(x = reorder(State, -meanABV), y = meanABV)) + geom_bar(stat = "identity") + 
  labs(x = "States", y = "Meadian ABV", title = "Meadian ABV by State")
```
```{r}

#If Budweiser wants to market or make Ale, here are the states Budweiser should look into. 
mergedBall %>% group_by(State) %>% summarise(meanIBU = mean(IBU)) %>% arrange(desc(meanIBU)) %>% 
  ggplot(aes(x = reorder(State, -meanIBU), y = meanIBU)) + geom_bar(stat = "identity") + 
  labs(x = "States", y = "Meadian IBU", title = "Meadian IBU by State")

```
